name: Crash
description: The game has a problem when AnimFix is present
title: "[Bug]: "
labels: ["bug"]
assignees:
  - falsepattern
body:
# Optional, only for mods that do stuff with rendering/native code
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What kind of operating system do you have?
      options:
        - Windows
        - Linux/BSD
        - MacOS
    validations:
      required: true
# Optional, only for graphics mods
  - type: dropdown
    id: gpu
    attributes:
      label: GPU
      description: What kind of graphics card do you have? If you have multiple, select the one that minecraft uses, you can usually find it somewhere at the top of the crash report.
      options:
        - AMD
        - NVIDIA
        - Intel
    validations:
      required: true
# Recommended for precise context
  - type: input
    id: modpack
    attributes:
      label: Modpack (Optional)
      description: If you used the mod in a modpack, you should include the pack's exact name and version here to make debugging easier.
    validations:
      required: false
# Essential
  - type: textarea
    id: logs
    attributes:
      label: Game log
      description: Attach the fml-client-latest.log file here.
    validations:
      required: true
# Essential
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how and when you experience this bug.
    validations:
      required: false